/**
 * İLANLAR — Tüm metin, özellik, fotoğraf ve video buradan düzenlenir.
 *
 * FOTOĞRAF DOSYALARI (önerilen klasör):
 *   assets/ilan-fotograflari/
 * Örnek: "assets/ilan-fotograflari/daire-1-mutfak.jpg"
 * İsterseniz doğrudan internet adresi (https://...) da yazabilirsiniz.
 *
 * VİDEO:
 *   YouTube (videoUrl): "Paylaş" → "Yerleştir" → iframe src veya watch?v= / youtu.be linki.
 *     Detay sayfasında "Video" düğmesiyle açılır.
 *   MP4 (videoMp4): assets/ilan-videolari/dosya.mp4 veya https://... adresi.
 *     Detay sayfasında galerinin en üstünde (fotoğraflardan önce) oynatılır.
 *   İkisi de boşsa video gösterilmez.
 *
 * Satılık ve kiralık ilanlar aynı alanları kullanır; sadece "type" ve rozet metni farklıdır.
 *
 * Liste: ilanlar.html — Detay: ilan-detay.html?id=ilanın_id_değeri
 *
 * HARİTA (detayda, küçük resim şeridinin hemen altında):
 *   mapsEmbedUrl — Google Haritalar: konum → Paylaş → Haritayı yerleştir → iframe içindeki
 *   src="https://..." adresini kopyalayıp buraya yapıştırın (tırnaklı string, iframe etiketi değil).
 *   Boş string ("") bırakırsanız o ilanda harita gösterilmez. Satılık / kiralık aynı alanı kullanır.
 *
 * LİSTE KARTI (kısa özet, yatay kart):
 *   listingNo     — Doluysa görselin üzerinde küçük numara
 *   listingDate   — Fiyatın sağında (örn. "12 Nisan 2026")
 *   cardLocationShort — Alt ikon satırı: konum (örn. "İstanbul / Kadıköy")
 *   cardArea      — m² metni (örn. "120 m²"); boşsa specs içinden m² satırı aranır
 *   cardRooms     — oda (örn. "3+1"); boşsa specs içinden "Oda" aranır
 */
var ILANLAR_DATA = [
  {
    id: "1",
    type: "satilik",
    title: "Kadıköy Four Winds 32.Kat Manzaralı Satılık Fırsat 1+1 Boş Daire",
    price: "21.950.000 TL ",
    location: "İstanbul / Kadıköy / Göztepe Mh.",
    listingNo: "",
    listingDate: "11 Nisan 2026",
    cardLocationShort: "İstanbul / Kadıköy",
    cardArea: "117 m²",
    cardRooms: "1+1",
    photos: [
      "assets/ilan-fotograflari/fourwinds/1.png",
      "assets/ilan-fotograflari/fourwinds/2.png",
      "assets/ilan-fotograflari/fourwinds/3.png",
      "assets/ilan-fotograflari/fourwinds/4.png",
      "assets/ilan-fotograflari/fourwinds/5.png",
      "assets/ilan-fotograflari/fourwinds/6.png",
      "assets/ilan-fotograflari/fourwinds/7.png",
      "assets/ilan-fotograflari/fourwinds/8.png",
      "assets/ilan-fotograflari/fourwinds/11.png",
      "assets/ilan-fotograflari/fourwinds/12.png",
      "assets/ilan-fotograflari/fourwinds/13.png",
      "assets/ilan-fotograflari/fourwinds/14.png",
      "assets/ilan-fotograflari/fourwinds/15.png",
      "assets/ilan-fotograflari/fourwinds/16.png",
      "assets/ilan-fotograflari/fourwinds/17.png",
      "assets/ilan-fotograflari/fourwinds/18.png",
      "assets/ilan-fotograflari/fourwinds/19.png",
      "assets/ilan-fotograflari/fourwinds/20.png",
      "assets/ilan-fotograflari/fourwinds/21.png",
      "assets/ilan-fotograflari/fourwinds/22.png",
      "assets/ilan-fotograflari/fourwinds/23.png",
      "assets/ilan-fotograflari/fourwinds/24.png",
      "assets/ilan-fotograflari/fourwinds/25.png",
      "assets/ilan-fotograflari/fourwinds/26.png",
      "assets/ilan-fotograflari/fourwinds/27.png",
      "assets/ilan-fotograflari/fourwinds/28.png",
      "assets/ilan-fotograflari/fourwinds/29.png",
      "assets/ilan-fotograflari/fourwinds/30.png",
      "assets/ilan-fotograflari/fourwinds/31.png",
      "assets/ilan-fotograflari/fourwinds/32.png",
      "assets/ilan-fotograflari/fourwinds/33.png",
      "assets/ilan-fotograflari/fourwinds/34.png",
    ],
    mapsEmbedUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3012.233400027378!2d29.051946975916472!3d40.97636977135506!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac7e8b7ae9a65%3A0xc7c3f84db7b6417d!2zVGHFnyB5YXBp!5e0!3m2!1sen!2str!4v1776087549906!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Kadıköy’de, Four Winds Residence’ta yer alan bu 32. kat, Adalar manzaralı 1+1 satılık daire, kaçırılmayacak bir fırsat sunmaktadır. İstanbul Anadolu Yakası’nın en prestijli projelerinden biri olan, Taşyapı imzalı bu özel yaşam alanında siz de yerinizi alabilirsiniz. Proje; açık ve kapalı otopark, 24 saat güvenlik hizmeti, açık yüzme havuzu ve çocuk havuzu gibi olanakların yanı sıra spor salonu, sauna ve hamam gibi sosyal imkanlar da sunmaktadır. Ayrıca basketbol sahaları ve site içi yürüyüş alanları ile hem aktif hem de konforlu bir yaşam imkanı sağlamaktadır. Konum olarak oldukça avantajlı olan proje, Bağdat Caddesi’ne yakın olup; banka, hastane, okul ve marketlere yürüme mesafesindedir. Toplu ulaşım açısından da herhangi bir sorun bulunmamakta olup, şehir içi erişim oldukça kolaydır. Kaliteli ve prestijli bir yaşam arayanlar için özel olarak tasarlanmış bu projede yerinizi almak için geç kalmayın. Tek yetkili: TURYAP ATAŞEHİR İMZA – Erol Erdoğar.",
    specs: [
      { label: "Emlak tipi", value: "Kiralık daire" },
      { label: "m² (Brüt / Net)", value: "117 / 87" },
      { label: "Oda sayısı", value: "1+1" },
      { label: "Bina yaşı", value: "6–10 arası" },
      { label: "Bulunduğu kat", value: "30 ve üzeri" },
      { label: "Isıtma", value: "Yerden Isıtma" },
      { label: "Banyo Sayısı", value: "2" },
      { label: "Mutfak", value: "Açık (Amerikan)" },
      { label: "Balkon", value: "Yok" },
      { label: "Asansör", value: "Var" },
      { label: "Otopark", value: "Açık & Kapalı Otopark" },
      { label: "Eşyalı", value: "Hayır" },
      { label: "Kullanım Durumu", value: "Boş" },
      { label: "Site İçerisinde", value: "Evet" },
      { label: "Site Adı", value: "Four Winds Residence" },
      { label: "Aidat (TL)", value: "7.500" },
      { label: "Krediye Uygun", value: "Hayır" },
      { label: "Tapu Durumu", value: "Kat Mülkiyetli" },
      { label: "Kimden", value: "Emlak Ofisinden" },
      { label: "Site Adı", value: "Four Winds Residence" },
      { label: "Takas", value: "Hayır" },


    ]
  },
    {
      id: "5",
      type: "kiralik",
      title: "Kadıköy Four Winds 32.Kat Manzaralı Kiralık Fırsat 1+1 Boş Daire",
      price: "97.500 TL ",
      location: "İstanbul / Kadıköy / Göztepe Mh.",
      listingNo: "",
      listingDate: "11 Nisan 2026",
      cardLocationShort: "İstanbul / Kadıköy",
      cardArea: "120 m²",
      cardRooms: "1+1",
      photos: [
        "assets/ilan-fotograflari/fourwinds/1.png",
        "assets/ilan-fotograflari/fourwinds/2.png",
        "assets/ilan-fotograflari/fourwinds/3.png",
        "assets/ilan-fotograflari/fourwinds/4.png",
        "assets/ilan-fotograflari/fourwinds/5.png",
        "assets/ilan-fotograflari/fourwinds/6.png",
        "assets/ilan-fotograflari/fourwinds/7.png",
        "assets/ilan-fotograflari/fourwinds/8.png",
        "assets/ilan-fotograflari/fourwinds/11.png",
        "assets/ilan-fotograflari/fourwinds/12.png",
        "assets/ilan-fotograflari/fourwinds/13.png",
        "assets/ilan-fotograflari/fourwinds/14.png",
        "assets/ilan-fotograflari/fourwinds/15.png",
        "assets/ilan-fotograflari/fourwinds/16.png",
        "assets/ilan-fotograflari/fourwinds/17.png",
        "assets/ilan-fotograflari/fourwinds/18.png",
        "assets/ilan-fotograflari/fourwinds/19.png",
        "assets/ilan-fotograflari/fourwinds/20.png",
        "assets/ilan-fotograflari/fourwinds/21.png",
        "assets/ilan-fotograflari/fourwinds/22.png",
        "assets/ilan-fotograflari/fourwinds/23.png",
        "assets/ilan-fotograflari/fourwinds/24.png",
        "assets/ilan-fotograflari/fourwinds/25.png",
        "assets/ilan-fotograflari/fourwinds/26.png",
        "assets/ilan-fotograflari/fourwinds/27.png",
        "assets/ilan-fotograflari/fourwinds/28.png",
        "assets/ilan-fotograflari/fourwinds/29.png",
        "assets/ilan-fotograflari/fourwinds/30.png",
        "assets/ilan-fotograflari/fourwinds/31.png",
        "assets/ilan-fotograflari/fourwinds/32.png",
        "assets/ilan-fotograflari/fourwinds/33.png",
        "assets/ilan-fotograflari/fourwinds/34.png",
      ],
    mapsEmbedUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3012.233400027378!2d29.051946975916472!3d40.97636977135506!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac7e8b7ae9a65%3A0xc7c3f84db7b6417d!2zVGHFnyB5YXBp!5e0!3m2!1sen!2str!4v1776087549906!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Kadıköy’de, Four Winds Residence’ta yer alan bu 32. kat, Adalar manzaralı 1+1 satılık daire, kaçırılmayacak bir fırsat sunmaktadır. İstanbul Anadolu Yakası’nın en prestijli projelerinden biri olan, Taşyapı imzalı bu özel yaşam alanında siz de yerinizi alabilirsiniz. Proje; açık ve kapalı otopark, 24 saat güvenlik hizmeti, açık yüzme havuzu ve çocuk havuzu gibi olanakların yanı sıra spor salonu, sauna ve hamam gibi sosyal imkanlar da sunmaktadır. Ayrıca basketbol sahaları ve site içi yürüyüş alanları ile hem aktif hem de konforlu bir yaşam imkanı sağlamaktadır. Konum olarak oldukça avantajlı olan proje, Bağdat Caddesi’ne yakın olup; banka, hastane, okul ve marketlere yürüme mesafesindedir. Toplu ulaşım açısından da herhangi bir sorun bulunmamakta olup, şehir içi erişim oldukça kolaydır. Kaliteli ve prestijli bir yaşam arayanlar için özel olarak tasarlanmış bu projede yerinizi almak için geç kalmayın. Tek yetkili: TURYAP ATAŞEHİR İMZA – Erol Erdoğar.",
    specs: [
      { label: "Emlak tipi", value: "Kiralık daire" },
      { label: "m² (Brüt / Net)", value: "117 / 87" },
      { label: "Oda sayısı", value: "1+1" },
      { label: "Bina yaşı", value: "6–10 arası" },
      { label: "Bulunduğu kat", value: "30 ve üzeri" },
      { label: "Isıtma", value: "Yerden Isıtma" },
      { label: "Banyo Sayısı", value: "2" },
      { label: "Mutfak", value: "Açık (Amerikan)" },
      { label: "Balkon", value: "Yok" },
      { label: "Asansör", value: "Var" },
      { label: "Otopark", value: "Açık & Kapalı Otopark" },
      { label: "Eşyalı", value: "Hayır" },
      { label: "Kullanım Durumu", value: "Boş" },
      { label: "Site İçerisinde", value: "Evet" },
      { label: "Site Adı", value: "Four Winds Residence" },
      { label: "Aidat (TL)", value: "7.500" },
      { label: "Krediye Uygun", value: "Hayır" },
      { label: "Tapu Durumu", value: "Kat Mülkiyetli" },
      { label: "Kimden", value: "Emlak Ofisinden" },
      { label: "Site Adı", value: "Four Winds Residence" },
      { label: "Takas", value: "Hayır" },


    ]
  },
  {
    id: "2",
    type: "satilik",
    title: "Kadıköy Fortis Sinanlı Rezidans 160 M2 Satılık Fırsat Dükkan",
    price: "31.500.000 TL  ",
    location: "İstanbul / Kadıköy / Fikirtepe Mah.",
    listingNo: "",
    listingDate: "31 Mart 2026",
    cardLocationShort: "İstanbul / Kadıköy",
    cardArea: "160 m²",
    cardRooms: "1",
    photos: [



    
      "assets/ilan-fotograflari/fortisinanli/2.png",
      "assets/ilan-fotograflari/fortisinanli/1.png",
      "assets/ilan-fotograflari/fortisinanli/3.png",
      "assets/ilan-fotograflari/fortisinanli/4.png",
      "assets/ilan-fotograflari/fortisinanli/5.png",
      "assets/ilan-fotograflari/fortisinanli/6.png",
      "assets/ilan-fotograflari/fortisinanli/7.png",
      "assets/ilan-fotograflari/fortisinanli/8.png",
      "assets/ilan-fotograflari/fortisinanli/9.png",
      "assets/ilan-fotograflari/fortisinanli/10.png",
      "assets/ilan-fotograflari/fortisinanli/11.png",
      "assets/ilan-fotograflari/fortisinanli/12.png",
      "assets/ilan-fotograflari/fortisinanli/13.png",
      "assets/ilan-fotograflari/fortisinanli/14.png",
      "assets/ilan-fotograflari/fortisinanli/15.png",
      "assets/ilan-fotograflari/fortisinanli/16.png",
      "assets/ilan-fotograflari/fortisinanli/17.png",
      "assets/ilan-fotograflari/fortisinanli/18.png",
      "assets/ilan-fotograflari/fortisinanli/19.png",
      "assets/ilan-fotograflari/fortisinanli/20.png",
      "assets/ilan-fotograflari/fortisinanli/21.png",
      "assets/ilan-fotograflari/fortisinanli/22.png",
      "assets/ilan-fotograflari/fortisinanli/23.png",
      "assets/ilan-fotograflari/fortisinanli/24.png",
      "assets/ilan-fotograflari/fortisinanli/25.png",
    ],
    
    mapsEmbedUrl:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3011.473134252605!2d29.043812775917264!3d40.993016371352645!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac78a9ee8ef69%3A0xedd0029a7a5b6761!2zRm9ydGlzIFNpbmFubMSxIFllbmkgS2FkxLFrw7Z5!5e0!3m2!1sen!2str!4v1776169399319!5m2!1sen!2str",
    videoUrl: "",
    videoMp4: "assets/ilan-fotograflari/fortisinanli/final.mp4",
    description:
      "KADIKÖY FİKİRTEPE – FORTİS SİNANLI REZİDANS 160 m² SATILIK | YÜKSEK TABELA DEĞERLİ FIRSAT DÜKKAN.İstanbul’un yükselen değeri Fikirtepe’de, prestijli Fortis Sinanlı Rezidans projesinde yer alan bu özel dükkan, yatırım ve ticaret için büyük fırsat sunuyor. 📍 Konum Avantajı: Ana cadde ve AVM bağlantılı cephe,Yoğun yaya ve araç trafiği,Toplu ulaşıma son derece yakın, ulaşım sorunu yok🏢 Özellikler:160 m² geniş kullanım alanı,Yüksek tavanlı, ferah mimari,AVM & rezidans konseptiyle prestijli çevre,Yüksek tabela ve görünürlük değeri,İstanbul’un kalbinin attığı bu bölgede, işinizi bir adım öne taşıyacak konumda yerinizi hemen alın.⏳ Fırsatı kaçırmayın, zaman daralıyor!📞 Detaylı bilgi ve randevu için:TURYAP ATAŞEHİR İMZA · Erol Erdoğar",
    specs: [
      { label: "Kategori", value: "İş Yeri" },
      { label: "Durumu", value: "Satılık" },
      { label: "Türü", value: "Dükkan & Mağaza" },
      { label: "m² (Net) ", value: "160" },
      { label: "Bölüm & Oda Sayısı", value: "1" },
      { label: "Bina yaşı", value: "4" },
      { label: "Isıtma", value: "Klima" },
      { label: "Aidat (TL)", value: "9.750" },
      { label: "Krediye Uygun", value: "Evet" },
      { label: "Tapu Durumu", value: "Kat Mülkiyetli" },
      { label: "Kimden", value: "Emlak Ofisinden" },
      { label: "Site Adı", value: "Fortis Sinanlı Rezidans" },
      { label: "Takas", value: "Hayır" },


    ]
  },
  
  {
    id: "3",
    type: "kiralik",
    title: "Fikirtepe 216 Rezidans Faal Devren Kiralık Burger Pizza Dükkanı",
    price: "1.650.000 TL",
    location: "İstanbul / Kadıköy / Dumlupınar Mh.",
    listingDate: "18 Nisan 2026",
    cardLocationShort: "İstanbul / Kadıköy ",
    cardArea: "45 m²",
    cardRooms: "2+1",
    photos: [
      "assets/ilan-fotograflari/216rezidans/1.png",
      "assets/ilan-fotograflari/216rezidans/2.png",
      "assets/ilan-fotograflari/216rezidans/3.png",
      "assets/ilan-fotograflari/216rezidans/4.png",
      "assets/ilan-fotograflari/216rezidans/5.png",
      "assets/ilan-fotograflari/216rezidans/6.png",
      "assets/ilan-fotograflari/216rezidans/7.png",
      "assets/ilan-fotograflari/216rezidans/8.png",
      "assets/ilan-fotograflari/216rezidans/9.png",
      "assets/ilan-fotograflari/216rezidans/10.png",
      "assets/ilan-fotograflari/216rezidans/11.png",
      "assets/ilan-fotograflari/216rezidans/12.png",
      "assets/ilan-fotograflari/216rezidans/13.png",
      "assets/ilan-fotograflari/216rezidans/14.png",
      "assets/ilan-fotograflari/216rezidans/15.png",
      "assets/ilan-fotograflari/216rezidans/16.png",
      "assets/ilan-fotograflari/216rezidans/17.png",
      "assets/ilan-fotograflari/216rezidans/18.png",
      
    ],
    mapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1505.7016220562377!2d29.05843361064741!3d40.99454639004521!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac79053b05a65%3A0x76d85de70c23bc30!2sBurger%20216!5e0!3m2!1sen!2str!4v1776530109238!5m2!1sen!2str",
    videoUrl: "",
    description: "DEVREN KİRALIK HAMBURGER & PİZZA STORE İstanbul’un parlayan yıldızı Fikirtepe’de, Baysaş 216 Rezidans’ın altında yer alan, faal durumda ve markasını oluşturmuş hamburger & pizza dükkanımız devren kiralıktır. Bölgedeki yaklaşık 20 rezidansın ortak noktasında bulunan işletmemiz, çevrede tanınan ve hazır müşteri kitlesine sahip bir konumdadır. Dükkanımızın hemen önünde yer alan ve önümüzdeki üç ay içerisinde oturuma başlayacak 1000’den fazla daire sayesinde müşteri potansiyeli her geçen gün artmaktadır. Yürüme mesafesinde yoğun bir yaşam alanı bulunmakta olup, bu da işletmenin gelecekteki kazanç potansiyelini yükseltmektedir. Her türlü ekipmanın eksiksiz bulunduğu salonumuz, işleyişe hazır ve aktif olarak hizmet vermektedir. Tüm bu avantajlarıyla birlikte hamburger & pizza store işletmemiz devren kiralıktır.Tek yetkili: TURYAP ATAŞEHİR İMZA – Erol Erdoğar.",
    specs: [
      { label: "Emlak tipi", value: "İş Yeri" },
      { label: "m²", value: "45" },
      { label: "Türü", value: "Restoran & Lokanta" },
      { label: "Bina Yaşı", value: "5-10 arası" },
      { label: "Isıtma", value: "Merkezi (Pay Ölçer)" },      
      { label: "Masa Sayısı", value: "10" },      
      { label: "Kimden", value: "Emlak Ofisinden" },     
      { label: "Durumu", value: "İkinci El" },
    ]
  },
  {
    id: "4",
    type: "kiralik",
    title: "Pendik Dumlupınar Gözdağı Manzaralı Balkonlu Kiralık 2+1 Daire",
    price: "34.500 TL ",
    location: "İstanbul / Pendik / Dumlupınar Mh.",
    listingDate: "15 Nisan 2026",
    cardLocationShort: "İstanbul / Pendik",
    cardArea: "125 m²",
    cardRooms: "2+1",
    photos: [
      "assets/ilan-fotograflari/Pendik/1.png",
      "assets/ilan-fotograflari/Pendik/2.png",
      "assets/ilan-fotograflari/Pendik/3.png",
      "assets/ilan-fotograflari/Pendik/4.png",
      "assets/ilan-fotograflari/Pendik/5.png",
      "assets/ilan-fotograflari/Pendik/6.png",
      "assets/ilan-fotograflari/Pendik/7.png",
      "assets/ilan-fotograflari/Pendik/8.png",
      "assets/ilan-fotograflari/Pendik/9.png",
      "assets/ilan-fotograflari/Pendik/10.png",
      "assets/ilan-fotograflari/Pendik/11.png",
      "assets/ilan-fotograflari/Pendik/12.png",
      "assets/ilan-fotograflari/Pendik/13.png",
      "assets/ilan-fotograflari/Pendik/14.png",
      "assets/ilan-fotograflari/Pendik/15.png",
      "assets/ilan-fotograflari/Pendik/16.png",
      "assets/ilan-fotograflari/Pendik/17.png",
      "assets/ilan-fotograflari/Pendik/18.png",
      "assets/ilan-fotograflari/Pendik/19.png",
      "assets/ilan-fotograflari/Pendik/20.png",
      "assets/ilan-fotograflari/Pendik/21.png",
      "assets/ilan-fotograflari/Pendik/22.png",
      "assets/ilan-fotograflari/Pendik/23.png",
      "assets/ilan-fotograflari/Pendik/24.png",
      "assets/ilan-fotograflari/Pendik/25.png",
      "assets/ilan-fotograflari/Pendik/26.png",
      "assets/ilan-fotograflari/Pendik/27.png",
      "assets/ilan-fotograflari/Pendik/28.png",
      "assets/ilan-fotograflari/Pendik/29.png",
      "assets/ilan-fotograflari/Pendik/30.png",
      "assets/ilan-fotograflari/Pendik/31.png",
      "assets/ilan-fotograflari/Pendik/32.png",

    ],
    mapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d754.0154629880965!2d29.2493226696218!3d40.89245809821044!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cadb005c1fa829%3A0x92a2ed8c50c59666!2zR8O2emRhxJ_EsSBBcGFydG1hbsSx!5e0!3m2!1sen!2str!4v1776587875994!5m2!1sen!2str",
    videoUrl: "",
    description: "Pendik Dumlupınar Gözdağı Manzaralı Balkonlu Kiralık 2+1 Daire.BÖLGE VE KONUM: İstanbul’un parlayan yıldızı Pendik’te, Muhteşem Adalar manzaralı, Anadolu Yakası’nın en temiz havasına sahip Gözdağı’nda, Toplu ulaşım sorunu olmayan harika bir projede yer almaktadır. Okul, hastane, banka ve marketler yanı başınızda olup, Kalitenin ve huzurun kesiştiği özel bir lokasyondadır.PROJE VE DAİRE ÖZELLİKLERİ:Kare ve kullanışlı plan yapısına sahip binamız,Geniş ve ferah girişli, çift asansörlüdür. Kapalı mutfaklı, Balkonlu ve çift banyolu bu harika dairemiz, Kapalı ve açık otopark imkânına sahip bir binada yer almaktadır. Ailenizle keyifle vakit geçirebileceğiniz, Temiz ve bakımlı bir bahçeye sahip, Güvenilir bir yaşam alanı sunmaktadır. Dairemiz siz değerli müşterilerimizi beklemektedir. Tek Yetkili: TURYAP ATAŞEHİR İMZA  Erol Erdoğar",
    specs: [
      { label: "Emlak tipi", value: "Kiralık daire" },
      { label: "m² (Brüt / Net)", value: "125 / 100" },
      { label: "Oda sayısı", value: "2+1" },
      { label: "Bina yaşı", value: "5" },
      { label: "Bulunduğu kat", value: "6" },
      { label: "Kat sayısı", value: "8" },
      { label: "Isıtma", value: "Kombi (Doğalgaz)" },
      { label: "Banyo Sayısı", value: "2" },
      { label: "Mutfak", value: "Kapalı" },
      { label: "Balkon", value: "Var" },
      { label: "Asansör", value: "Var" },
      { label: "Otopark", value: "Açık & Kapalı Otopark" },
      { label: "Eşyalı", value: "Hayır" },
      { label: "Kullanım Durumu", value: "Boş" },
      { label: "Site İçerisinde", value: "Hayır" },
      { label: "Site Adı", value: "Belirtilmemiş" },
      { label: "Aidat (TL)", value: "600" },
      { label: "Depozito (TL)", value: "30.000" },
      { label: "Tapu Durumu", value: "Kat Mülkiyeti" },
      { label: "Kimden", value: "Emlak Ofisinden" },
    ]
  },
  {
    id: "6",
    type: "kiralik",
    title: "Ünalan Cadde Üstü Tabela Değerli Balkonlu 90 m² Kiralık 2+1 Daire",
    price: "31.500 TL ",
    location: "İstanbul / Üsküdar / Ünalan Mh.",
    listingDate: "14 Nisan 2026",
    cardLocationShort: "İstanbul / Üsküdar",
    cardArea: "90 m²",
    cardRooms: "2+1",
    photos: [

    "assets/ilan-fotograflari/Ünalan/1.png",
    "assets/ilan-fotograflari/Ünalan/2.png",
    "assets/ilan-fotograflari/Ünalan/3.png",
    "assets/ilan-fotograflari/Ünalan/4.png",
    "assets/ilan-fotograflari/Ünalan/5.png",
    "assets/ilan-fotograflari/Ünalan/6.png",
    "assets/ilan-fotograflari/Ünalan/7.png",
    "assets/ilan-fotograflari/Ünalan/8.png",
    "assets/ilan-fotograflari/Ünalan/9.png",
    "assets/ilan-fotograflari/Ünalan/10.png",
    "assets/ilan-fotograflari/Ünalan/11.png",
    "assets/ilan-fotograflari/Ünalan/12.png",
    "assets/ilan-fotograflari/Ünalan/13.png",
    "assets/ilan-fotograflari/Ünalan/14.png",
    "assets/ilan-fotograflari/Ünalan/15.png",
    "assets/ilan-fotograflari/Ünalan/16.png",
    "assets/ilan-fotograflari/Ünalan/17.png",


    ],
    mapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d188.19094657519!2d29.065905487023645!3d41.00216619037832!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac7e6d9c4cf87%3A0x480158e21cb0f23f!2zw5xuYWxhbiwgw5xsZ2VuIFNrLiBObzoyLCAzNDcwMCDDnHNrw7xkYXIvxLBzdGFuYnVs!5e0!3m2!1sen!2str!4v1776675820163!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Üsküdar Ünalan’da cadde üstü konumda bulunan 90 m², balkonlu kiralık 2+1 fırsat daire; İstanbul’un parlayan bölgelerinden Ünalan’da yer almakta olup toplu ulaşıma kolay erişim imkânı sunar. Okul, banka, market ve hastaneler yanı başında, Emaar AVM ve metroya yürüme mesafesindedir. Tek yetkili: TURYAP ATAŞEHİR İMZA – Erol Erdoğar",
    specs: [
      { label: "Emlak tipi", value: "Kiralık daire" },
      { label: "m² (Brüt / Net)", value: "90 / 80" },
      { label: "Oda sayısı", value: "2+1" },
      { label: "Bina yaşı", value: "21–25 arası" },
      { label: "Bulunduğu kat", value: "1" },
      { label: "Kat sayısı", value: "2" },
      { label: "Isıtma", value: "Kombi (Doğalgaz)" },
      { label: "Banyo Sayısı", value: "2" },
      { label: "Mutfak", value: "Kapalı" },
      { label: "Balkon", value: "Var" },
      { label: "Asansör", value: "Yok" },
      { label: "Otopark", value: "Yok" },
      { label: "Eşyalı", value: "Hayır" },
      { label: "Kullanım Durumu", value: "Boş" },
      { label: "Site İçerisinde", value: "Hayır" },
      { label: "Site Adı", value: "Belirtilmemiş" },
      { label: "Aidat (TL)", value: "Belirtilmemiş" },
      { label: "Depozito (TL)", value: "Belirtilmemiş" },
      { label: "Tapu Durumu", value: "Kat Mülkiyeti" },
      { label: "Kimden", value: "Emlak Ofisinden" },
    ],
  },
  {
    id: "8",
    type: "kiralik",
    title: "Sarphan Finans Merkezi 70 M2 Özel Teraslı Kiralık FIRSAT İşyeri",
    price: "39.500 TL ",
    location: "İstanbul / Ümraniye / Finanskent Mh.",
    listingDate: "13 Nisan 2026",
    cardLocationShort: "İstanbul / Ümraniye",
    cardArea: "70 m²",
    cardRooms: "1+0",
    photos: [

      "assets/ilan-fotograflari/Sarphan/1.png",
      "assets/ilan-fotograflari/Sarphan/2.png",
      "assets/ilan-fotograflari/Sarphan/3.png",
      "assets/ilan-fotograflari/Sarphan/4.png",
      "assets/ilan-fotograflari/Sarphan/5.png",
      "assets/ilan-fotograflari/Sarphan/6.png",
      "assets/ilan-fotograflari/Sarphan/7.png",
      "assets/ilan-fotograflari/Sarphan/8.png",
      "assets/ilan-fotograflari/Sarphan/9.png",
      "assets/ilan-fotograflari/Sarphan/10.png",
      "assets/ilan-fotograflari/Sarphan/11.png",
      "assets/ilan-fotograflari/Sarphan/12.png",
    ],
    mapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1505.4674815713033!2d29.104568974926845!3d41.00479667571882!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac9c6b095c617%3A0x3929328026660228!2sHedef%20Ltd!5e0!3m2!1sen!2str!4v1776677058765!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Ümraniye Finanskent’te Sarphan Finans Merkezi’nde, özel terası bulunan 70 m² kiralık işyeri; merkezi ısıtma (pay ölçer), 3. kat konumu ve yüksek standartlı rezidans/ofis çevresiyle öne çıkar. Detay ve gösterim için iletişime geçebilirsiniz. Tek yetkili: TURYAP ATAŞEHİR İMZA — Erol Erdoğar.",
    specs: [
      { label: "Emlak tipi", value: "Kiralık iş yeri" },
      { label: "m²", value: "70" },
      { label: "Oda sayısı", value: "1+0" },
      { label: "Bina yaşı", value: "4" },
      { label: "Bulunduğu kat", value: "3" },
      { label: "Isıtma", value: "Merkezi (Pay Ölçer)" },
      { label: "Aidat (TL)", value: "9.900" },
      { label: "Depozito (TL)", value: "Belirtilmemiş" },
      { label: "Tapu Durumu", value: "Kat Mülkiyetli" },
      { label: "Kimden", value: "Emlak Ofisinden" },
    ],
  },
  {
    id: "9",
    type: "kiralik",
    title: "Kadıköy Baysaş 216 Rezidans Full Eşyalı 2+1 Lüks Kiralık Daire",
    price: "67.500 TL ",
    location: "İstanbul / Kadıköy / Dumlupınar Mh.",
    listingDate: "13 Nisan 2026",
    cardLocationShort: "İstanbul / Kadıköy",
    cardArea: "111 m²",
    cardRooms: "2+1",
    photos: [

       "assets/ilan-fotograflari/216/1.png",
       "assets/ilan-fotograflari/216/2.png",
       "assets/ilan-fotograflari/216/3.png",
       "assets/ilan-fotograflari/216/4.png",
       "assets/ilan-fotograflari/216/5.png",
       "assets/ilan-fotograflari/216/6.png",
       "assets/ilan-fotograflari/216/7.png",
       "assets/ilan-fotograflari/216/8.png",
       "assets/ilan-fotograflari/216/9.png",
       "assets/ilan-fotograflari/216/10.png",
       "assets/ilan-fotograflari/216/11.png",
       "assets/ilan-fotograflari/216/12.png",
       "assets/ilan-fotograflari/216/13.png",
       "assets/ilan-fotograflari/216/14.png",
       "assets/ilan-fotograflari/216/15.png",
       "assets/ilan-fotograflari/216/16.png",
       "assets/ilan-fotograflari/216/17.png",
    




    ],
    mapsEmbedUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d752.8559323596437!2d29.059694100802925!3d40.99409793492099!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac7f22394ff5d%3A0xf45d47595ad3b115!2s%C4%B0stanbul%20216%202.%20Etap!5e0!3m2!1sen!2str!4v1776678710014!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Kadıköy Fikirtepe’de Baysaş 216 (İstanbul 216) Rezidans’ta yer alan, kare ve kullanışlı planlı, full eşyalı kiralık 2+1 lüks daire; özel tasarım dolaplar ve mobilyalarla, yüksek kaliteli eşyalarla döşenmiş olup kısa dönem kiralamaya öncelikli olarak uygundur.Fikirtepe’de Baysaş 216 Rezidans (İstanbul 216 2. Etap) içinde, full eşyalı, lüks 2+1 kiralık daire; 16. katta, merkezi ısıtma (pay ölçer), asansör ve açık otopark imkânlarıyla hazır yaşam sunar. Amerikan mutfak, site içi konfor ve Kadıköy’ün yükselen bölgesinde konum. Detay ve gösterim için iletişime geçebilirsiniz. Tek yetkili: TURYAP ATAŞEHİR İMZA — Erol Erdoğar.",
    specs: [
      { label: "Emlak tipi", value: "Kiralık daire" },
      { label: "m² (Brüt / Net)", value: "111 / 73" },
      { label: "Oda sayısı", value: "2+1" },
      { label: "Bina yaşı", value: "6–10 arası" },
      { label: "Bulunduğu kat", value: "16" },
      { label: "Kat sayısı", value: "23" },
      { label: "Isıtma", value: "Merkezi (Pay Ölçer)" },
      { label: "Banyo Sayısı", value: "1" },
      { label: "Mutfak", value: "Açık (Amerikan)" },
      { label: "Balkon", value: "Yok" },
      { label: "Asansör", value: "Var" },
      { label: "Otopark", value: "Açık Otopark" },
      { label: "Eşyalı", value: "Evet" },
      { label: "Kullanım Durumu", value: "Boş" },
      { label: "Site İçerisinde", value: "Evet" },
      { label: "Site Adı", value: "İstanbul 216 2. Etap" },
      { label: "Aidat (TL)", value: "Belirtilmemiş" },
      { label: "Depozito (TL)", value: "Belirtilmemiş" },
      { label: "Tapu Durumu", value: "Kat Mülkiyetli" },
      { label: "Kimden", value: "Emlak Ofisinden" },
    ],
  },
  {
    id: "10",
    type: "kiralik",
    title: "Kadıköy Fikirtepe Teknik Yapı Concord Cadde 75M2 Kiralık Dükkan",
    price: "130.000 TL ",
    location: "İstanbul / Kadıköy / Dumlupınar Mh.",
    listingDate: "13 Nisan 2026",
    cardLocationShort: "İstanbul / Kadıköy",
    cardArea: "75 m²",
    photos: [
      "assets/ilan-fotograflari/Concord/1.png",
      "assets/ilan-fotograflari/Concord/2.png",
      "assets/ilan-fotograflari/Concord/3.png",
      "assets/ilan-fotograflari/Concord/4.png",
      "assets/ilan-fotograflari/Concord/5.png",
      "assets/ilan-fotograflari/Concord/6.png",
      "assets/ilan-fotograflari/Concord/7.png",
      "assets/ilan-fotograflari/Concord/8.png",
      "assets/ilan-fotograflari/Concord/9.png",
      "assets/ilan-fotograflari/Concord/10.png",
      "assets/ilan-fotograflari/Concord/11.png",
      "assets/ilan-fotograflari/Concord/12.png",
      "assets/ilan-fotograflari/Concord/13.png",
      "assets/ilan-fotograflari/Concord/14.png",
      "assets/ilan-fotograflari/Concord/15.png",
      "assets/ilan-fotograflari/Concord/16.png",
      "assets/ilan-fotograflari/Concord/17.png",
      "assets/ilan-fotograflari/Concord/18.png",
      "assets/ilan-fotograflari/Concord/19.png"


    ],
    mapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1505.7120200529378!2d29.061715321495925!3d40.994091133907475!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac70a0f524b91%3A0x3c2afbcef1e9478!2sConcord%20Istanbul!5e0!3m2!1sen!2str!4v1776681983067!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Kadıköy Fikirtepe’de Teknik Yapı Concord projesinde, cadde üstü konumda yer alan 75 m² dükkan & mağaza; kafe ve tekel konseptine uygun olup toplu ulaşımın merkezinde bulunmaktadır. Geniş cepheli, tabela değeri yüksek olan iş yerimiz daha önce kafe olarak kullanılmış olup ruhsat altyapısı hazırdır. Site içi ve çevre yoğunluğu sayesinde yüksek müşteri potansiyeline sahiptir. İç mekân iki bölümlü (ofis + satış alanı / mutfak + servis alanı) olarak avantajlı kullanım sunar. 5–10 yıllık binada, giriş katta yer alan dükkan klimalıdır ve 5,5 m ön cephe, 7 m yan cephe genişliğine sahiptir. 1 ay ücretsiz kira ile tadilat izni verilmektedir. Not: Kira yıllık peşin talep edilmekte olup teklife göre görüşülür. TURYAP ATAŞEHİR İMZA – Erol Erdoğar.",
    specs: [
      { label: "Kategori", value: "İş Yeri" },
      { label: "Durumu", value: "Kiralık" },
      { label: "Türü", value: "Kafe & Bar" },
      { label: "m²", value: "75" },
      { label: "Bina yaşı", value: "5–10 arası" },
      { label: "Isıtma", value: "Klima" },
      { label: "Alkol ruhsatı", value: "Var" },
      { label: "Aidat (TL)", value: "6.000" },
      { label: "Depozito (TL)", value: "300.000" },
      { label: "Tapu Durumu", value: "Kat Mülkiyetli" },
      { label: "Kimden", value: "Emlak Ofisinden" },
    ],
  },
  {
    id: "11",
    type: "kiralik",
    title: "Dumankaya İkon Rezidans Eşyalı 78 m² Kiralık 2+1 Fırsat Daire",
    price: "48.500 TL ",
    location: "İstanbul / Ataşehir / Örnek Mh.",
    listingDate: "12 Nisan 2026",
    cardLocationShort: "İstanbul / Ataşehir",
    cardArea: "78 m²",
    cardRooms: "2+1",
    photos: [

    "assets/ilan-fotograflari/icon/1.png",
    "assets/ilan-fotograflari/icon/2.png",
    "assets/ilan-fotograflari/icon/3.png",
    "assets/ilan-fotograflari/icon/4.png",
    "assets/ilan-fotograflari/icon/5.png",
    "assets/ilan-fotograflari/icon/6.png",
    "assets/ilan-fotograflari/icon/7.png",
    "assets/ilan-fotograflari/icon/8.png",
    "assets/ilan-fotograflari/icon/9.png",
    "assets/ilan-fotograflari/icon/10.png",
    "assets/ilan-fotograflari/icon/11.png",
    "assets/ilan-fotograflari/icon/12.png",
    "assets/ilan-fotograflari/icon/13.png",
    "assets/ilan-fotograflari/icon/14.png",
    "assets/ilan-fotograflari/icon/15.png",
    "assets/ilan-fotograflari/icon/16.png",
    "assets/ilan-fotograflari/icon/17.png",
    "assets/ilan-fotograflari/icon/18.png",
    "assets/ilan-fotograflari/icon/19.png",
    "assets/ilan-fotograflari/icon/20.png",
    "assets/ilan-fotograflari/icon/21.png",
    "assets/ilan-fotograflari/icon/22.png",
    "assets/ilan-fotograflari/icon/23.png",
    "assets/ilan-fotograflari/icon/24.png",
    "assets/ilan-fotograflari/icon/25.png",
    "assets/ilan-fotograflari/icon/26.png",
    "assets/ilan-fotograflari/icon/27.png",
    "assets/ilan-fotograflari/icon/28.png",
    "assets/ilan-fotograflari/icon/29.png",
    "assets/ilan-fotograflari/icon/30.png",

    ],
    mapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1505.7498660976314!2d29.084323385984163!3d40.992434083027874!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac70002091861%3A0xdac292f7b3275963!2sDumankaya%20Ikon!5e0!3m2!1sen!2str!4v1776706529018!5m2!1sen!2str",
  
    videoUrl: "",
    description:
      "Ataşehir Örnek Mahallesi’nde Dumankaya İkon Rezidans’ta, eşyalı, boş teslim 2+1 kiralık daire; 5. katta, merkezi ısıtma (pay ölçer), asansör ve açık–kapalı otopark ile site yaşamı sunar. Amerikan mutfak, yüksek katlı modern proje ve ulaşım avantajı. Detay ve gösterim için iletişime geçebilirsiniz. Tek yetkili: TURYAP ATAŞEHİR İMZA — Erol Erdoğar.",
    specs: [
      { label: "Emlak tipi", value: "Kiralık daire" },
      { label: "m² (Brüt / Net)", value: "78 / 60" },
      { label: "Oda sayısı", value: "2+1" },
      { label: "Bina yaşı", value: "11–15 arası" },
      { label: "Bulunduğu kat", value: "5" },
      { label: "Kat sayısı", value: "30 ve üzeri" },
      { label: "Isıtma", value: "Merkezi (Pay Ölçer)" },
      { label: "Banyo Sayısı", value: "1" },
      { label: "Mutfak", value: "Açık (Amerikan)" },
      { label: "Balkon", value: "Yok" },
      { label: "Asansör", value: "Var" },
      { label: "Otopark", value: "Açık & Kapalı Otopark" },
      { label: "Eşyalı", value: "Evet" },
      { label: "Kullanım Durumu", value: "Boş" },
      { label: "Site İçerisinde", value: "Evet" },
      { label: "Site Adı", value: "Dumankaya İkon" },
      { label: "Aidat (TL)", value: "Belirtilmemiş" },
      { label: "Depozito (TL)", value: "Belirtilmemiş" },
      { label: "Tapu Durumu", value: "Kat Mülkiyetli" },
      { label: "Kimden", value: "Emlak Ofisinden" },
    ],
  },
  {
    id: "12",
    type: "satilik",
    title:
      "Pendik Ahmet Yesevi Merkez 90 m² Bahçe Katı Satılık Fırsat Boş Daire",
    price: "2.950.000 TL ",
    location: "İstanbul / Pendik / Ahmet Yesevi Mah.",
    listingDate: "30 Ocak 2026",
    cardLocationShort: "İstanbul / Pendik",
    cardArea: "90 m²",
    cardRooms: "2+1",
    photos: [


       "assets/ilan-fotograflari/Pendik1/1.png",
       "assets/ilan-fotograflari/Pendik1/2.png",
       "assets/ilan-fotograflari/Pendik1/3.png",
       "assets/ilan-fotograflari/Pendik1/4.png",
       "assets/ilan-fotograflari/Pendik1/5.png",
       "assets/ilan-fotograflari/Pendik1/6.png",
       "assets/ilan-fotograflari/Pendik1/7.png",
       "assets/ilan-fotograflari/Pendik1/8.png",
       "assets/ilan-fotograflari/Pendik1/9.png",
       "assets/ilan-fotograflari/Pendik1/10.png",
       "assets/ilan-fotograflari/Pendik1/11.png",
       "assets/ilan-fotograflari/Pendik1/12.png",
       "assets/ilan-fotograflari/Pendik1/13.png",
       "assets/ilan-fotograflari/Pendik1/14.png",
       "assets/ilan-fotograflari/Pendik1/15.png",
       "assets/ilan-fotograflari/Pendik1/16.png",
       "assets/ilan-fotograflari/Pendik1/17.png",
       "assets/ilan-fotograflari/Pendik1/18.png",
       "assets/ilan-fotograflari/Pendik1/19.png",
       "assets/ilan-fotograflari/Pendik1/20.png",





    ],
    mapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d377.14628964092157!2d29.31061597258175!3d40.86813635926026!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2str!4v1777331167362!5m2!1sen!2strhttps://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d754.2944241732409!2d29.309969469602805!3d40.86797439821064!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cadbf7000042f3%3A0x40c0d6ed0ee68c82!2sAhmet%20Yesevi%2C%20Silvan%20Sk.%20No%3A11%2C%2034903%20Pendik%2F%C4%B0stanbul!5e0!3m2!1sen!2str!4v1777331250235!5m2!1sen!2str",
    videoUrl: "",
    description: "Pendik Ahmet Yesevi Mahallesi’nde merkezi konumda yer alan 90 m² bahçe katı satılık fırsat boş daire; Pendik’in yükselen bölgelerinden birinde, en güzel mahallelerinden Ahmet Yesevi’de bulunmaktadır. Krediye uygun olan dairemiz kısa süreliğine indirimde olup yeşillikler içinde hemen taşınıp oturulabilecek durumdadır. Bankalar, marketler, hastane ve okullar yanı başında, toplu ulaşıma kolay erişim sağlayan avantajlı konumuyla dikkat çekmektedir.",
    specs: [
      { label: "Emlak tipi", value: "Satılık daire" },
      { label: "m² (Brüt / Net)", value: "100 / 90" },
      { label: "Oda sayısı", value: "2+1" },
      { label: "Bina yaşı", value: "16–20 arası" },
      { label: "Bulunduğu kat", value: "Bahçe katı" },
      { label: "Kat sayısı", value: "3" },
      { label: "Isıtma", value: "Kombi (Doğalgaz)" },
      { label: "Banyo Sayısı", value: "1" },
      { label: "Mutfak", value: "Kapalı" },
      { label: "Balkon", value: "Yok" },
      { label: "Asansör", value: "Yok" },
      { label: "Otopark", value: "Yok" },
      { label: "Eşyalı", value: "Hayır" },
      { label: "Kullanım Durumu", value: "Boş" },   
      { label: "Site İçerisinde", value: "Hayır" },
      { label: "Site Adı", value: "Belirtilmemiş" },
      { label: "Aidat (TL)", value: "Belirtilmemiş" },
      { label: "Krediye Uygun", value: "Evet" },
      { label: "Enerji Kimlik Belgesi", value: "Belirtilmemiş" },
      { label: "Tapu Durumu", value: "Kat İrtifaklı" },
      { label: "Kimden", value: "Emlak Ofisinden" },
      { label: "Takas", value: "Evet" },
    ],
  },
  {
    id: "13",
    type: "satilik",
    title:
      "Ataşehir Dumankaya İkon 39. Kat Eşyalı Satılık 1+0 Stüdyo Boş Daire",
    price: "5.150.000 TL ",
    location: "İstanbul / Ataşehir / Örnek Mh.",
    listingDate: "29 Ocak 2026",
    cardLocationShort: "İstanbul / Ataşehir",
    cardArea: "25 m²",
    cardRooms: "1+0",
    photos: [


    "assets/ilan-fotograflari/icon1/1.png",
    "assets/ilan-fotograflari/icon1/2.png",
    "assets/ilan-fotograflari/icon1/3.png",
    "assets/ilan-fotograflari/icon1/4.png",
    "assets/ilan-fotograflari/icon1/5.png",
    "assets/ilan-fotograflari/icon1/6.png",
    "assets/ilan-fotograflari/icon1/7.png",
    "assets/ilan-fotograflari/icon1/8.png",
    "assets/ilan-fotograflari/icon1/9.png",
    "assets/ilan-fotograflari/icon1/10.png",
    "assets/ilan-fotograflari/icon1/11.png",
    "assets/ilan-fotograflari/icon1/12.png",
    "assets/ilan-fotograflari/icon1/13.png",
    "assets/ilan-fotograflari/icon1/14.png",
    "assets/ilan-fotograflari/icon1/15.png",
    "assets/ilan-fotograflari/icon1/16.png",
    "assets/ilan-fotograflari/icon1/17.png",
    "assets/ilan-fotograflari/icon1/18.png",
    "assets/ilan-fotograflari/icon1/19.png",
    "assets/ilan-fotograflari/icon1/20.png",
    "assets/ilan-fotograflari/icon1/21.png",
    "assets/ilan-fotograflari/icon1/22.png",



    ],
    mapsEmbedUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1505.7498660976314!2d29.084323385984163!3d40.992434083027874!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac70002091861%3A0xdac292f7b3275963!2sDumankaya%20Ikon!5e0!3m2!1sen!2str!4v1776706529018!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Ataşehir Dumankaya İkon’da 39. katta yer alan, muhteşem manzaralı full eşyalı satılık 1+0 daire; İstanbul manzarasını ayaklarınızın altına seren, toplu ulaşıma kolay erişimli harika bir konumda bulunmaktadır. Şehrin içinde tatil keyfi sunan rezidansta yer alan dairemiz, özel dizayn giriş ve oda dolaplarıyla A’dan Z’ye full eşyalı olarak satışa sunulmaktadır. Marmara, Bahçeşehir, Okan, Acıbadem ve Medeniyet Üniversitelerine yakın konumda olup metro, Marmaray ve metrobüs gibi ulaşım ağlarına kolay erişim sağlamaktadır, ayrıca Avrasya Tüneli çıkışına yakın lokasyondadır. Detaylı bilgi için: TURYAP ATAŞEHİR İMZA – Erol Erdoğar.",
    specs: [
      { label: "Emlak tipi", value: "Satılık daire" },
      { label: "m² (Brüt / Net)", value: "31 / 25" },
      { label: "Oda sayısı", value: "Stüdyo (1+0)" },
      { label: "Bina yaşı", value: "16–20 arası" },
      { label: "Bulunduğu kat", value: "30 ve üzeri" },
      { label: "Kat sayısı", value: "30 ve üzeri" },
      { label: "Isıtma", value: "Merkezi (Pay Ölçer)" },
      { label: "Banyo Sayısı", value: "1" },
      { label: "Mutfak", value: "Açık (Amerikan)" },
      { label: "Balkon", value: "Yok" },
      { label: "Asansör", value: "Var" },
      { label: "Otopark", value: "Kapalı Otopark" },
      { label: "Eşyalı", value: "Evet" },
      { label: "Kullanım Durumu", value: "Boş" },
      { label: "Site İçerisinde", value: "Evet" },
      { label: "Site Adı", value: "Dumankaya İkon" },
      { label: "Aidat (TL)", value: "Belirtilmemiş" },
      { label: "Krediye Uygun", value: "Evet" },
      { label: "Enerji Kimlik Belgesi", value: "Belirtilmemiş" },
      { label: "Tapu Durumu", value: "Kat Mülkiyetli" },
      { label: "Kimden", value: "Emlak Ofisinden" },
      { label: "Takas", value: "Evet" },
    ],
  },
  {
    id: "14",
    type: "satilik",
    title:
      "Ataşehir İkon Residence 60 m² Manzaralı Satılık 1+1 Fırsat Daire",
    price: "6.790.000 TL ",
    location: "İstanbul / Ataşehir / Örnek Mh.",
    listingDate: "01 Mart 2026",
    cardLocationShort: "İstanbul / Ataşehir",
    cardArea: "45 m²",
    cardRooms: "1+1",
    photos: [


      "assets/ilan-fotograflari/icon2/1.png",
      "assets/ilan-fotograflari/icon2/2.png",
      "assets/ilan-fotograflari/icon2/3.png",
      "assets/ilan-fotograflari/icon2/4.png",
      "assets/ilan-fotograflari/icon2/5.png",
      "assets/ilan-fotograflari/icon2/6.png",
      "assets/ilan-fotograflari/icon2/7.png",
      "assets/ilan-fotograflari/icon2/8.png",
      "assets/ilan-fotograflari/icon2/9.png",
      "assets/ilan-fotograflari/icon2/10.png",
      "assets/ilan-fotograflari/icon2/11.png",
      "assets/ilan-fotograflari/icon2/12.png",
      "assets/ilan-fotograflari/icon2/13.png",
      "assets/ilan-fotograflari/icon2/14.png",
      "assets/ilan-fotograflari/icon2/15.png",
      "assets/ilan-fotograflari/icon2/16.png",
      "assets/ilan-fotograflari/icon2/17.png",
      "assets/ilan-fotograflari/icon2/18.png",
      "assets/ilan-fotograflari/icon2/19.png",
      "assets/ilan-fotograflari/icon2/20.png",




    ],
    mapsEmbedUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1505.7498660976314!2d29.084323385984163!3d40.992434083027874!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac70002091861%3A0xdac292f7b3275963!2sDumankaya%20Ikon!5e0!3m2!1sen!2str!4v1776706529018!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Ataşehir Örnek Mahallesi’nde Dumankaya İkon Residence’ta yer alan, yüksek katta panoramik manzaralı 45 m² net (62 m² brüt) satılık 1+1 fırsat daire; eşyasız teslim görüşülür. Merkezi ısıtma (pay ölçer), asansör, açık ve kapalı otopark; Amerikan mutfak, kiracılı kullanımda olup detay görüşülür. Krediye uygun, kat mülkiyeti. Takas yapılmamaktadır. Detay ve gösterim için iletişime geçebilirsiniz. RE/MAX İmza.",
    specs: [
      { label: "Emlak tipi", value: "Satılık daire" },
      { label: "m² (Brüt / Net)", value: "62 / 45" },
      { label: "Oda sayısı", value: "1+1" },
      { label: "Bina yaşı", value: "16–20 arası" },
      { label: "Bulunduğu kat", value: "30 ve üzeri" },
      { label: "Kat sayısı", value: "30 ve üzeri" },
      { label: "Isıtma", value: "Merkezi (Pay Ölçer)" },
      { label: "Banyo Sayısı", value: "1" },
      { label: "Mutfak", value: "Açık (Amerikan)" },
      { label: "Balkon", value: "Yok" },
      { label: "Asansör", value: "Var" },
      { label: "Otopark", value: "Açık & Kapalı Otopark" },
      { label: "Eşyalı", value: "Hayır" },
      { label: "Kullanım Durumu", value: "Kiracılı" },
      { label: "Site İçerisinde", value: "Evet" },
      { label: "Site Adı", value: "Dumankaya İkon" },
      { label: "Aidat (TL)", value: "Belirtilmemiş" },
      { label: "Krediye Uygun", value: "Evet" },
      { label: "Enerji Kimlik Belgesi", value: "Belirtilmemiş" },
      { label: "Tapu Durumu", value: "Kat Mülkiyetli" },
      { label: "Kimden", value: "Emlak Ofisinden" },
      { label: "Takas", value: "Hayır" },
    ],
  },
  {
    id: "15",
    type: "satilik",
    title:
      "Ataşehir Örnek Dumankaya Yanı 75 m² Satılık Fırsat 2+1 Daire",
    price: "5.525.000 TL ",
    location: "İstanbul / Ataşehir / Örnek Mh.",
    listingDate: "01 Mart 2026",
    cardLocationShort: "İstanbul / Ataşehir",
    cardArea: "60 m²",
    cardRooms: "2+1",
    photos: [

      "assets/ilan-fotograflari/ornek/1.png",
      "assets/ilan-fotograflari/ornek/2.png",
      "assets/ilan-fotograflari/ornek/3.png",
      "assets/ilan-fotograflari/ornek/4.png",
      "assets/ilan-fotograflari/ornek/5.png",
      "assets/ilan-fotograflari/ornek/6.png",
      "assets/ilan-fotograflari/ornek/7.png",
      "assets/ilan-fotograflari/ornek/8.png", 
      "assets/ilan-fotograflari/ornek/9.png",
      "assets/ilan-fotograflari/ornek/10.png",
      "assets/ilan-fotograflari/ornek/11.png",
      "assets/ilan-fotograflari/ornek/12.png",
      "assets/ilan-fotograflari/ornek/13.png",
      "assets/ilan-fotograflari/ornek/14.png",
      "assets/ilan-fotograflari/ornek/15.png",
      "assets/ilan-fotograflari/ornek/16.png",
      "assets/ilan-fotograflari/ornek/17.png",
      "assets/ilan-fotograflari/ornek/18.png",
      "assets/ilan-fotograflari/ornek/19.png",

    ],
    mapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d752.8568372335014!2d29.086811669622133!3d40.994018698209516!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac7d23aa730b3%3A0xf0edc8b6b63df30b!2zw5ZybmVrLCBCYXlyYWtsxLEgU29rYcSfxLEsIDM0NzA0IEF0YcWfZWhpci_EsHN0YW5idWw!5e0!3m2!1sen!2str!4v1777332809568!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Ataşehir Örnek Mahallesi’nde, Dumankaya İkon çevresinde konumlanan 4 katlı yapıda; yüksek giriş katta yer alan 60 m² net (75 m² brüt) satılık 2+1 fırsat daire. Merkezi ısıtma (pay ölçer), asansör, Amerikan mutfak; balkon ve otopark yok. Boş teslim, site dışı konumda aidat yükü belirtilmemiştir. Krediye uygun, kat mülkiyetli tapu; takas görüşülür. Detay ve gösterim için iletişime geçebilirsiniz. RE/MAX İmza.",
    specs: [
      { label: "Emlak tipi", value: "Satılık daire" },
      { label: "m² (Brüt / Net)", value: "75 / 60" },
      { label: "Oda sayısı", value: "2+1" },
      { label: "Bina yaşı", value: "6–10 arası" },
      { label: "Bulunduğu kat", value: "Yüksek giriş" },
      { label: "Kat sayısı", value: "4" },
      { label: "Isıtma", value: "Merkezi (Pay Ölçer)" },
      { label: "Banyo Sayısı", value: "1" },
      { label: "Mutfak", value: "Açık (Amerikan)" },
      { label: "Balkon", value: "Yok" },
      { label: "Asansör", value: "Var" },
      { label: "Otopark", value: "Yok" },
      { label: "Eşyalı", value: "Hayır" },
      { label: "Kullanım Durumu", value: "Boş" },
      { label: "Site İçerisinde", value: "Hayır" },
      { label: "Site Adı", value: "Belirtilmemiş" },
      { label: "Aidat (TL)", value: "Belirtilmemiş" },
      { label: "Krediye Uygun", value: "Evet" },
      { label: "Enerji Kimlik Belgesi", value: "Belirtilmemiş" },
      { label: "Tapu Durumu", value: "Kat Mülkiyetli" },
      { label: "Kimden", value: "Emlak Ofisinden" },
      { label: "Takas", value: "Evet" },
    ],
  },
  {
    id: "16",
    type: "satilik",
    title:
      "Kadıköy Fikirtepe Teknik Yapı Concord Rezidans Satılık 1+1 Daire",
    price: "6.950.000 TL ",
    location: "İstanbul / Kadıköy / Dumlupınar Mh.",
    listingDate: "17 Şubat 2026",
    cardLocationShort: "İstanbul / Kadıköy",
    cardArea: "44 m²",
    cardRooms: "1+1",
    photos: [

    "assets/ilan-fotograflari/Concord1/1.png",
    "assets/ilan-fotograflari/Concord1/2.png",
    "assets/ilan-fotograflari/Concord1/3.png",
    "assets/ilan-fotograflari/Concord1/4.png",
    "assets/ilan-fotograflari/Concord1/5.png",
    "assets/ilan-fotograflari/Concord1/6.png",
    "assets/ilan-fotograflari/Concord1/7.png",
    "assets/ilan-fotograflari/Concord1/8.png",
    "assets/ilan-fotograflari/Concord1/9.png",
    "assets/ilan-fotograflari/Concord1/10.png",
    "assets/ilan-fotograflari/Concord1/11.png",
    "assets/ilan-fotograflari/Concord1/12.png",
    "assets/ilan-fotograflari/Concord1/13.png",
    "assets/ilan-fotograflari/Concord1/14.png",
    "assets/ilan-fotograflari/Concord1/15.png",
    "assets/ilan-fotograflari/Concord1/16.png",
    "assets/ilan-fotograflari/Concord1/17.png",
    "assets/ilan-fotograflari/Concord1/18.png",
    "assets/ilan-fotograflari/Concord1/19.png",
    "assets/ilan-fotograflari/Concord1/20.png",
    "assets/ilan-fotograflari/Concord1/21.png",
    "assets/ilan-fotograflari/Concord1/22.png",
    "assets/ilan-fotograflari/Concord1/23.png",
    "assets/ilan-fotograflari/Concord1/24.png",
    "assets/ilan-fotograflari/Concord1/25.png",






    ],
    mapsEmbedUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1505.7120200529378!2d29.061715321495925!3d40.994091133907475!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac70a0f524b91%3A0x3c2afbcef1e9478!2sConcord%20Istanbul!5e0!3m2!1sen!2str!4v1776681983067!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Kadıköy Fikirtepe Concord projesinde 60 m² yüksek katta yer alan satılık boş 1+1 daire; İstanbul’un parlayan yıldızı Fikirtepe’de, toplu ulaşıma kolay erişim sağlayan harika bir projede bulunmaktadır. Göztepe E-5 bölgesinde yer alan daire, Kadıköy merkeze 8 dk, Bağdat Caddesi’ne 7 dk, Pendik-Kadıköy hattına 2 dk, Göztepe Köprüsü’ne 5 dk ve Sabiha Gökçen Havalimanı’na 30 dk mesafede olup ulaşım avantajı sunmaktadır. Site içerisinde kapalı ve açık yüzme havuzu, fitness center, Türk hamamı, sauna, dinlenme alanları, kapalı otopark ve 7/24 güvenlik gibi sosyal donatılar mevcuttur. Ayrıca The Mandarins Acıbadem, Usta İnşaat 1071 Kadıköy, Baysaş İstanbul 216, Nuhoğlu Yenitepe, Anka Evim Kadıköy, Sefa İnşaat Evinpark Kadıköy ve Pırlanta Göztepe projelerinde de satılık ve kiralık alternatiflerimiz bulunmaktadır. Detaylı bilgi için: RE/MAX İmza – Kadıköy Bölge Uzmanı Erol Erdoğar 0532 566 28 38.",
    specs: [
      { label: "Emlak tipi", value: "Satılık daire" },
      { label: "m² (Brüt / Net)", value: "59 / 44" },
      { label: "Oda sayısı", value: "1+1" },
      { label: "Bina yaşı", value: "6–10 arası" },
      { label: "Bulunduğu kat", value: "21" },
      { label: "Kat sayısı", value: "23" },
      { label: "Isıtma", value: "Merkezi (Pay Ölçer)" },
      { label: "Banyo Sayısı", value: "1" },
      { label: "Mutfak", value: "Açık (Amerikan)" },
      { label: "Balkon", value: "Yok" },
      { label: "Asansör", value: "Yok" },
      { label: "Otopark", value: "Açık & Kapalı Otopark" },
      { label: "Eşyalı", value: "Hayır" },
      { label: "Kullanım Durumu", value: "Mülk sahibi" },
      { label: "Site İçerisinde", value: "Evet" },
      { label: "Site Adı", value: "Concord İstanbul" },
      { label: "Aidat (TL)", value: "2.350" },
      { label: "Krediye Uygun", value: "Evet" },
      { label: "Enerji Kimlik Belgesi", value: "Belirtilmemiş" },
      { label: "Tapu Durumu", value: "Kat Mülkiyetli" },
      { label: "Kimden", value: "Emlak Ofisinden" },
      { label: "Takas", value: "Hayır" },
    ],
  },
  {
    id: "17",
    type: "satilik",
    title:
      "Ataşehir Örnek Merkez Metro Yanı 80 m² Satılık 2+1 Fırsat Daire",
    price: "6.290.000 TL ",
    location: "İstanbul / Ataşehir / Örnek Mh.",
    listingDate: "25 Nisan 2026",
    cardLocationShort: "İstanbul / Ataşehir",
    cardArea: "75 m²",
    cardRooms: "2+1",
    photos: [


      "assets/ilan-fotograflari/ornek1/1.png",
      "assets/ilan-fotograflari/ornek1/2.png",
      "assets/ilan-fotograflari/ornek1/3.png",
      "assets/ilan-fotograflari/ornek1/4.png",
      "assets/ilan-fotograflari/ornek1/5.png",
      "assets/ilan-fotograflari/ornek1/6.png",
      "assets/ilan-fotograflari/ornek1/7.png",
      "assets/ilan-fotograflari/ornek1/8.png",
      "assets/ilan-fotograflari/ornek1/9.png",
      "assets/ilan-fotograflari/ornek1/10.png",
      "assets/ilan-fotograflari/ornek1/11.png",
      "assets/ilan-fotograflari/ornek1/12.png",
      "assets/ilan-fotograflari/ornek1/13.png",
      "assets/ilan-fotograflari/ornek1/14.png",
      "assets/ilan-fotograflari/ornek1/15.png",
      "assets/ilan-fotograflari/ornek1/16.png",
      "assets/ilan-fotograflari/ornek1/17.png",
      "assets/ilan-fotograflari/ornek1/18.png",
      "assets/ilan-fotograflari/ornek1/19.png",
      "assets/ilan-fotograflari/ornek1/20.png",
      "assets/ilan-fotograflari/ornek1/22.png",
      "assets/ilan-fotograflari/ornek1/23.png",
      "assets/ilan-fotograflari/ornek1/24.png",
      "assets/ilan-fotograflari/ornek1/25.png",
      "assets/ilan-fotograflari/ornek1/26.png",
      "assets/ilan-fotograflari/ornek1/27.png",
      "assets/ilan-fotograflari/ornek1/28.png",
      








    ],
    mapsEmbedUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d752.8522532782274!2d29.07648856962213!3d40.99442009820954!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac7c4d09d834b%3A0x513845a9fb8e4559!2zw5ZybmVrLCBBYmTDvGxrZXJpbSDFnmViaWsgU2suIE5vOjI5LCAzNDcwNCBBdGHFn2VoaXIvxLBzdGFuYnVs!5e0!3m2!1sen!2str!4v1777333901780!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Ataşehir Örnek Mahallesi’nde, metro yanı ve merkezi konumda yer alan 80 m² satılık 2+1 fırsat daire; E-5 ve metroya yürüme mesafesinde, toplu ulaşımın merkezinde bulunmaktadır. Önü açık, ferah ve ayrık düzende konumlanmış binada yer alan dairemizde karanlık oda bulunmamakta olup tüm odalar gün ışığı almaktadır. Örnek Mahallesi’nin en güzel ve geniş sokaklarından birinde bulunan, temiz kullanılmış ve değer katılmış bu daire; okul, hastane, banka ve marketlere yürüme mesafesindedir. Kullanışlı ve kare planlı yüksek giriş dairemiz konforlu bir yaşam sunmaktadır. Not: Binada iskan alınmış olup dairelere henüz yansıtılmamıştır. Detaylı bilgi için: TURYAP ATAŞEHİR İMZA – Erol Erdoğar.",
    specs: [
      { label: "Emlak tipi", value: "Satılık daire" },
      { label: "m² (Brüt / Net)", value: "80 / 75" },
      { label: "Oda sayısı", value: "2+1" },
      { label: "Bina yaşı", value: "11–15 arası" },
      { label: "Bulunduğu kat", value: "Yüksek giriş" },
      { label: "Kat sayısı", value: "3" },
      { label: "Isıtma", value: "Kombi (Doğalgaz)" },
      { label: "Banyo Sayısı", value: "1" },
      { label: "Mutfak", value: "Açık (Amerikan)" },
      { label: "Balkon", value: "Yok" },
      { label: "Asansör", value: "Yok" },
      { label: "Otopark", value: "Açık Otopark" },
      { label: "Eşyalı", value: "Hayır" },
      { label: "Kullanım Durumu", value: "Mülk sahibi" },
      { label: "Site İçerisinde", value: "Hayır" },
      { label: "Site Adı", value: "Belirtilmemiş" },
      { label: "Aidat (TL)", value: "Belirtilmemiş" },
      { label: "Krediye Uygun", value: "Evet" },
      { label: "Enerji Kimlik Belgesi", value: "Belirtilmemiş" },
      { label: "Tapu Durumu", value: "Kat İrtifaklı" },
      { label: "Kimden", value: "Emlak Ofisinden" },
      { label: "Takas", value: "Hayır" },
    ],
  },
  {
    id: "18",
    type: "satilik",
    title:
      "Ataşehir İkon Residence 120 m² Balkonlu Satılık 2+1 Dubleks Daire",
    price: "10.250.000 TL ",
    location: "İstanbul / Ataşehir / Örnek Mh.",
    listingDate: "25 Nisan 2026",
    cardLocationShort: "İstanbul / Ataşehir",
    cardArea: "90 m²",
    cardRooms: "2+1",
    photos: [


      "assets/ilan-fotograflari/icon3/1.png",
      "assets/ilan-fotograflari/icon3/2.png",
      "assets/ilan-fotograflari/icon3/3.png",
      "assets/ilan-fotograflari/icon3/4.png",
      "assets/ilan-fotograflari/icon3/5.png",
      "assets/ilan-fotograflari/icon3/6.png",
      "assets/ilan-fotograflari/icon3/7.png",
      "assets/ilan-fotograflari/icon3/8.png",
      "assets/ilan-fotograflari/icon3/9.png",
      "assets/ilan-fotograflari/icon3/10.png",
      "assets/ilan-fotograflari/icon3/11.png",
      "assets/ilan-fotograflari/icon3/12.png",
      "assets/ilan-fotograflari/icon3/13.png",
      "assets/ilan-fotograflari/icon3/14.png",
      "assets/ilan-fotograflari/icon3/15.png",
      "assets/ilan-fotograflari/icon3/16.png",
      "assets/ilan-fotograflari/icon3/17.png",
      "assets/ilan-fotograflari/icon3/18.png",
      "assets/ilan-fotograflari/icon3/19.png",
      "assets/ilan-fotograflari/icon3/20.png",
      "assets/ilan-fotograflari/icon3/21.png",
      "assets/ilan-fotograflari/icon3/22.png",
      "assets/ilan-fotograflari/icon3/23.png",
      "assets/ilan-fotograflari/icon3/24.png",
      "assets/ilan-fotograflari/icon3/25.png",
      "assets/ilan-fotograflari/icon3/26.png",
      "assets/ilan-fotograflari/icon3/27.png",
      "assets/ilan-fotograflari/icon3/28.png",
      "assets/ilan-fotograflari/icon3/29.png",
      "assets/ilan-fotograflari/icon3/30.png",





    ],
    mapsEmbedUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1505.7498660976314!2d29.084323385984163!3d40.992434083027874!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac70002091861%3A0xdac292f7b3275963!2sDumankaya%20Ikon!5e0!3m2!1sen!2str!4v1776706529018!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Ataşehir Dumankaya İkon’da balkonlu, full eşyalı satılık 2+1 dublex daire; toplu ulaşıma kolay erişim sağlayan, hastane, okul, AVM, banka ve marketlere yakın konumda yer alan prestijli bir projede bulunmaktadır. Muhteşem manzarası ve geniş balkonu ile keyifli bir yaşam sunan bu özel tip dublex daire, şehir hayatında tatil konforu yaşatmaktadır. Memorial, Medical Park, Medipol ve Göztepe Şehir Hastanesi gibi önemli sağlık kurumlarına; Bahçeşehir, Okan, Acıbadem, Medeniyet ve Doğuş Üniversitelerine yakın konumda olup metro, Marmaray ve metrobüs hatlarına kolay erişim imkânı sunmaktadır. Ayrıca Avrasya Tüneli çıkışına yakın, köprü bağlantıları arasında avantajlı bir lokasyondadır. Detaylı bilgi için: TURYAP ATAŞEHİR İMZA – Erol Erdoğar.",
    specs: [
      { label: "Emlak tipi", value: "Satılık daire" },
      { label: "m² (Brüt / Net)", value: "120 / 90" },
      { label: "Oda sayısı", value: "2+1" },
      { label: "Bina yaşı", value: "16–20 arası" },
      { label: "Bulunduğu kat", value: "30 ve üzeri" },
      { label: "Kat sayısı", value: "30 ve üzeri" },
      { label: "Isıtma", value: "Merkezi (Pay Ölçer)" },
      { label: "Banyo Sayısı", value: "1" },
      { label: "Mutfak", value: "Açık (Amerikan)" },
      { label: "Balkon", value: "Var" },
      { label: "Asansör", value: "Var" },
      { label: "Otopark", value: "Açık & Kapalı Otopark" },
      { label: "Eşyalı", value: "Evet" },
      { label: "Kullanım Durumu", value: "Boş" },
      { label: "Site İçerisinde", value: "Evet" },
      { label: "Site Adı", value: "Dumankaya İkon" },
      { label: "Aidat (TL)", value: "Belirtilmemiş" },
      { label: "Krediye Uygun", value: "Evet" },
      { label: "Enerji Kimlik Belgesi", value: "Belirtilmemiş" },
      { label: "Tapu Durumu", value: "Kat Mülkiyetli" },
      { label: "Kimden", value: "Emlak Ofisinden" },
      { label: "Takas", value: "Hayır" },
    ],
  },
  {
    id: "19",
    type: "satilik",
    title:
      "Sakarya Geyve Kirazlar Çift Cepheli 9.200 m² Satılık Fırsat Arazi",
    price: "4.850.000 TL ",
    location: "Sakarya / Geyve / Safibey Mh.",
    listingDate: "02 Mart 2026",
    cardLocationShort: "Sakarya / Geyve",
    cardArea: "9.200 m²",
    cardRooms: "",
    photos: [

  
      "assets/ilan-fotograflari/sakarya/1.png",
      "assets/ilan-fotograflari/sakarya/2.png",
      "assets/ilan-fotograflari/sakarya/3.png",
      "assets/ilan-fotograflari/sakarya/4.png",
      "assets/ilan-fotograflari/sakarya/5.png",
    


    ],
    mapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d189.66694110980103!2d30.244676358997825!3d40.48254167305974!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cc9ed3a4003bdf%3A0x70f28f40610ce428!2zxLBuY2lrc3V5dSwgw4dlbmdlbCBLw7Z5w7wgxLDDpyBZb2x1LCA1NDcwMCBHZXl2ZS9TYWthcnlh!5e0!3m2!1sen!2str!4v1777334763174!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Sakarya Geyve Kirazlar mevkiinde çift cepheli 9.200 m² satılık fırsat arazi; Sakarya’nın yükselen bölgelerinden Geyve’de, Safibey’e 900 metre, Geyve-Osmaneli yoluna 800 metre, Sakarya Nehri’ne 2,5 km, Geyve merkeze 5 km ve Pamukova’ya 6 km mesafede yer almaktadır. Verimli toprak yapısı sayesinde yatırım ve tarım için ideal olan bu arazi, hayallerinizi gerçeğe dönüştürebileceğiniz bir fırsat sunmaktadır. Detaylı bilgi için tek yetkili: TURYAP ATAŞEHİR İMZA – Erol Erdoğar.",
    specs: [
      { label: "Emlak tipi", value: "Satılık arsa" },
      { label: "İmar durumu", value: "Tarla + Bağ" },
      { label: "m²", value: "9.200" },
      { label: "m² fiyatı", value: "527 TL" },
      { label: "Ada no", value: "115" },
      { label: "Parsel no", value: "28" },
      { label: "Pafta no", value: "Belirtilmemiş" },
      { label: "Kaks (emsal)", value: "Belirtilmemiş" },
      { label: "Gabari", value: "Belirtilmemiş" },
      { label: "Krediye Uygun", value: "Evet" },
      { label: "Tapu Durumu", value: "Müstakil Tapu" },
      { label: "Kimden", value: "Emlak Ofisinden" },
      { label: "Takas", value: "Evet" },
    ],
  },
  {
    id: "20",
    type: "satilik",
    title:
      "Yalova Kazımiye Merkez TOKİ Yanı 446 m² Fırsat Arsa",
    price: "3.490.000 TL ",
    location: "Yalova / Merkez / Kazımiye Köyü",
    listingDate: "01 Mart 2026",
    cardLocationShort: "Yalova / Merkez",
    cardArea: "446 m²",
    cardRooms: "",
    photos: [


      "assets/ilan-fotograflari/yalova/1.png",
      "assets/ilan-fotograflari/yalova/2.png",
      "assets/ilan-fotograflari/yalova/3.png",
      "assets/ilan-fotograflari/yalova/4.png",
      "assets/ilan-fotograflari/yalova/5.png",
      "assets/ilan-fotograflari/yalova/6.png",

    ],
    mapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d756.9673959962431!2d29.310234569602073!3d40.632757998212846!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cafb4ff34f1fdf%3A0x5b58dba9ef688cbd!2zS2F6xLFtaXllIEvDtnnDvCDEsMOnIFlvbHUsIDc3MjAyIEthesSxbWl5ZS9ZYWxvdmEgTWVya2V6L1lhbG92YQ!5e0!3m2!1sen!2str!4v1777335180870!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Yalova Merkez Kazımiye’de, TOKİ yanı konumda yer alan 446 m² satılık fırsat arsa; bölgenin yükselen noktalarından birinde, geleceğe değerli bir yatırım imkânı sunmaktadır. Aynı zamanda bitişiğindeki ikinci parsel ile birlikte toplam 860 m² olarak da değerlendirilebilen bu arsa, 3 kat imarlı olup 0.75 emsal ve kot farkı avantajıyla ek kat kazanım potansiyeline sahiptir. 14.08.2025 tarihinde yer teslimi yapılacak 703 konut, 8 dükkan ve 1 camiden oluşan 2. etap TOKİ projesinin hemen yanında yer almakta olup, planlanan yol bağlantısı ile merkeze direkt ulaşım sağlanacaktır. Ayrıca konum itibarıyla lise, ortaokul ve ilkokul projelerine komşu olup bölgenin en cazip yatırım fırsatlarından biridir. Detaylı bilgi için: TURYAP ATAŞEHİR İMZA – Erol Erdoğar.",
    specs: [
      { label: "Emlak tipi", value: "Satılık arsa" },
      { label: "İmar durumu", value: "Konut" },
      { label: "m²", value: "446" },
      { label: "m² fiyatı", value: "7.825 TL" },
      { label: "Ada no", value: "127" },
      { label: "Parsel no", value: "4" },
      { label: "Pafta no", value: "Belirtilmemiş" },
      { label: "Kaks (emsal)", value: "0,75" },
      { label: "Gabari", value: "Belirtilmemiş" },
      { label: "Krediye Uygun", value: "Hayır" },
      { label: "Tapu Durumu", value: "Müstakil Tapu" },
      { label: "Kimden", value: "Emlak Ofisinden" },
      { label: "Takas", value: "Hayır" },
    ],
  },
  {
    id: "21",
    type: "satilik",
    title: "Ataşehir Esatpaşa Nestiva Satılık 150M2 Manzaralı 3+1 Dublex",
    price: "15.750.000 TL",
    location: "İstanbul / Ataşehir / Esatpaşa Mh.",
    listingDate: "05 Mayıs 2026",
    cardLocationShort: "İstanbul / Ataşehir",
    cardArea: "150 m²",
    cardRooms: "3+1",
    photos: [

      "assets/ilan-fotograflari/atasehir/1.png",
      "assets/ilan-fotograflari/atasehir/2.png",
      "assets/ilan-fotograflari/atasehir/3.png",
      "assets/ilan-fotograflari/atasehir/4.png",
      "assets/ilan-fotograflari/atasehir/5.png",
      "assets/ilan-fotograflari/atasehir/6.png",
      "assets/ilan-fotograflari/atasehir/7.png",
      "assets/ilan-fotograflari/atasehir/8.png",
      "assets/ilan-fotograflari/atasehir/9.png",
      "assets/ilan-fotograflari/atasehir/10.png",
      "assets/ilan-fotograflari/atasehir/11.png",
      "assets/ilan-fotograflari/atasehir/12.png",
      "assets/ilan-fotograflari/atasehir/13.png",
      "assets/ilan-fotograflari/atasehir/14.png",
      "assets/ilan-fotograflari/atasehir/15.png",
      "assets/ilan-fotograflari/atasehir/16.png",
      "assets/ilan-fotograflari/atasehir/17.png",
      "assets/ilan-fotograflari/atasehir/18.png",
      "assets/ilan-fotograflari/atasehir/19.png",
      "assets/ilan-fotograflari/atasehir/20.png",
      "assets/ilan-fotograflari/atasehir/21.png",
      "assets/ilan-fotograflari/atasehir/22.png",
      "assets/ilan-fotograflari/atasehir/23.png",
      "assets/ilan-fotograflari/atasehir/24.png",
      "assets/ilan-fotograflari/atasehir/25.png",
      "assets/ilan-fotograflari/atasehir/26.png",
      "assets/ilan-fotograflari/atasehir/27.png",
      "assets/ilan-fotograflari/atasehir/28.png",
      "assets/ilan-fotograflari/atasehir/29.png",
      "assets/ilan-fotograflari/atasehir/30.png",
      "assets/ilan-fotograflari/atasehir/31.png",
      "assets/ilan-fotograflari/atasehir/32.png",
      "assets/ilan-fotograflari/atasehir/33.png",
      "assets/ilan-fotograflari/atasehir/34.png",
      "assets/ilan-fotograflari/atasehir/35.png",
      "assets/ilan-fotograflari/atasehir/36.png",
      "assets/ilan-fotograflari/atasehir/37.png",
      "assets/ilan-fotograflari/atasehir/38.png",
      "assets/ilan-fotograflari/atasehir/39.png",
      "assets/ilan-fotograflari/atasehir/40.png",
      "assets/ilan-fotograflari/atasehir/41.png",
      "assets/ilan-fotograflari/atasehir/42.png",
      "assets/ilan-fotograflari/atasehir/43.png",
      "assets/ilan-fotograflari/atasehir/44.png",
      "assets/ilan-fotograflari/atasehir/45.png",
      "assets/ilan-fotograflari/atasehir/46.png",
      "assets/ilan-fotograflari/atasehir/47.png",
      "assets/ilan-fotograflari/atasehir/48.png",
      "assets/ilan-fotograflari/atasehir/49.png",
      "assets/ilan-fotograflari/atasehir/50.png",


    ],
    mapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d752.8028525378875!2d29.085896805316935!3d40.998745732923425!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac7d427f90e1f%3A0x9955ebf30def7edb!2sNestiva%20Ata%C5%9Fehir!5e0!3m2!1sen!2str!4v1778245292533!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Ataşehir Esatpaşa’da, Finansşehir’e komşu Nestiva Sitesi’nde yer alan 150 m² manzaralı ve teraslı satılık fırsat 3+1 dublex daire; şehir hayatında tatil konforu sunan özel bir yaşam alanı sunmaktadır. 4 blok ve 110 daireden oluşan güvenlikli sitemiz, 12.500 m² büyüklüğündeki Aşık Veysel Parkı’nın hemen yanında konumlanmakta olup banka, market, okul ve tıp merkezlerine yakınlığıyla dikkat çekmektedir. Üç cepheli, manzaralı ve elektrikli panjurlu geniş terasa sahip dairemizde çift giriş, 3 banyo ve multi klima sistemi bulunmaktadır. Kare ve kullanışlı odalarıyla öne çıkan dublex dairede salon 32.69 m², mutfak 11.38 m², ebeveyn odası 17.61 m² olup toplam kullanım alanı balkon dahil yaklaşık 135 m²’dir. Kaliteli yaşam için tüm detayların düşünüldüğü bu özel daire hakkında detaylı bilgi için: Tek Yetkili Turyap Ataşehir İmza – Erol Erdoğar.",
    specs: [
      { label: "İlan No", value: "1315223892" },
      { label: "İlan Tarihi", value: "05 Mayıs 2026" },
      { label: "Emlak tipi", value: "Satılık daire" },
      { label: "m² (Brüt / Net)", value: "150 / 132" },
      { label: "Oda sayısı", value: "3+1" },
      { label: "Bina yaşı", value: "6–10 arası" },
      { label: "Bulunduğu kat", value: "7" },
      { label: "Kat sayısı", value: "8" },
      { label: "Isıtma", value: "Kombi (Doğalgaz)" },
      { label: "Banyo Sayısı", value: "3" },
      { label: "Mutfak", value: "Kapalı" },
      { label: "Balkon", value: "Var" },
      { label: "Asansör", value: "Var" },
      { label: "Otopark", value: "Açık & Kapalı Otopark" },
      { label: "Eşyalı", value: "Hayır" },
      { label: "Kullanım Durumu", value: "Mülk Sahibi" },
      { label: "Site İçerisinde", value: "Evet" },
      { label: "Site Adı", value: "Nestiva Ataşehir" },
      { label: "Aidat (TL)", value: "5.000" },
      { label: "Krediye Uygun", value: "Evet" },
      { label: "Enerji Kimlik Belgesi", value: "Belirtilmemiş" },
      { label: "Tapu Durumu", value: "Kat Mülkiyetli" },
      { label: "Kimden", value: "Emlak Ofisinden" },
      { label: "Takas", value: "Hayır" },
    ],
  },
  {
    id: "22",
    type: "kiralik",
    title: "Kadıköy Fortis Sinanlı Rezidans Balkonlu Kiralık 1+0 Stüdyo Daire",
    price: "32.500 TL",
    location: "İstanbul / Kadıköy / Fikirtepe Mah.",
    listingDate: "07 Mayıs 2026",
    cardLocationShort: "İstanbul / Kadıköy",
    cardArea: "49 m²",
    cardRooms: "1+0",
    photos: [

    "assets/ilan-fotograflari/fortissinanli/1.png",
    "assets/ilan-fotograflari/fortissinanli/2.png",
    "assets/ilan-fotograflari/fortissinanli/3.png",
    "assets/ilan-fotograflari/fortissinanli/4.png",
    "assets/ilan-fotograflari/fortissinanli/5.png",
    "assets/ilan-fotograflari/fortissinanli/6.png",
    "assets/ilan-fotograflari/fortissinanli/7.png",
    "assets/ilan-fotograflari/fortissinanli/8.png",
    "assets/ilan-fotograflari/fortissinanli/9.png",
    "assets/ilan-fotograflari/fortissinanli/10.png",
    "assets/ilan-fotograflari/fortissinanli/11.png",
    "assets/ilan-fotograflari/fortissinanli/12.png",
    "assets/ilan-fotograflari/fortissinanli/13.png",
    "assets/ilan-fotograflari/fortissinanli/14.png",
    "assets/ilan-fotograflari/fortissinanli/15.png",
    "assets/ilan-fotograflari/fortissinanli/16.png",
    "assets/ilan-fotograflari/fortissinanli/17.png",
    "assets/ilan-fotograflari/fortissinanli/18.png",
    "assets/ilan-fotograflari/fortissinanli/19.png",
    "assets/ilan-fotograflari/fortissinanli/20.png",
    "assets/ilan-fotograflari/fortissinanli/21.png",



    ],
    mapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3011.473134252605!2d29.043812775917264!3d40.993016371352645!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac78a9ee8ef69%3A0xedd0029a7a5b6761!2zRm9ydGlzIFNpbmFubMSxIFllbmkgS2FkxLFrw7Z5!5e0!3m2!1sen!2str!4v1778245777891!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Kadıköy Fikirtepe’de, ödüllü Fortis Sinanlı Rezidans projesinde yer alan özel balkonlu kiralık 1+0 stüdyo daire; projenin en büyük balkonuna sahip özel tip seçeneklerinden biridir. Metrobüs yanı konumda bulunan rezidans, toplu ulaşıma kolay erişim sağlarken şehir hayatında tatil konforu sunmaktadır. Açık ve kapalı yüzme havuzu, SPA, fitness, sauna, buhar odası, hamam, vitamin bar, mini sinema salonu, hobi odası, çocuk oyun alanları ve vale hizmeti gibi sosyal olanaklara sahiptir. Akıllı ev sistemi, 3 metre tavan yüksekliği, resepsiyon, güvenlikli giriş çıkış, jeneratör, kapalı devre kamera sistemi, su deposu ve yüksek ses/ısı yalıtımı gibi ayrıcalıklı özellikleriyle konforlu bir yaşam sunmaktadır. Tek yetkili: RE/MAX İmza – Erol Erdoğar. Detaylı bilgi için iletişime geçiniz.",
    specs: [
      { label: "İlan No", value: "1241680125" },
      { label: "İlan Tarihi", value: "07 Mayıs 2026" },
      { label: "Emlak tipi", value: "Kiralık daire" },
      { label: "m² (Brüt / Net)", value: "49 / 36" },
      { label: "Oda sayısı", value: "Stüdyo (1+0)" },
      { label: "Bina yaşı", value: "3" },
      { label: "Bulunduğu kat", value: "1" },
      { label: "Kat sayısı", value: "23" },
      { label: "Isıtma", value: "Merkezi (Pay Ölçer)" },
      { label: "Banyo Sayısı", value: "1" },
      { label: "Mutfak", value: "Açık (Amerikan)" },
      { label: "Balkon", value: "Var" },
      { label: "Asansör", value: "Var" },
      { label: "Otopark", value: "Kapalı Otopark" },
      { label: "Eşyalı", value: "Hayır" },
      { label: "Kullanım Durumu", value: "Boş" },
      { label: "Site İçerisinde", value: "Evet" },
      { label: "Site Adı", value: "Fortis Sinanlı" },
      { label: "Aidat (TL)", value: "Belirtilmemiş" },
      { label: "Depozito (TL)", value: "Belirtilmemiş" },
      { label: "Enerji Kimlik Belgesi", value: "Belirtilmemiş" },
      { label: "Tapu Durumu", value: "Kat Mülkiyetli" },
      { label: "Kimden", value: "Emlak Ofisinden" },
    ],
  },
  {
    id: "23",
    type: "satilik",
    title: "Kadıköy Baysaş 216 Rezidans Eşyalı Satılık 2+1 Fırsat Köşe Daire",
    price: "12.250.000 TL",
    location: "İstanbul / Kadıköy / Dumlupınar Mh.",
    listingDate: "14 Mayıs 2026",
    cardLocationShort: "İstanbul / Kadıköy",
    cardArea: "90 m²",
    cardRooms: "2+1",
    photos: [

    "assets/ilan-fotograflari/216/1.png",
    "assets/ilan-fotograflari/216/2.png",
    "assets/ilan-fotograflari/216/3.png",
    "assets/ilan-fotograflari/216/4.png",
    "assets/ilan-fotograflari/216/5.png",
    "assets/ilan-fotograflari/216/6.png",
    "assets/ilan-fotograflari/216/7.png",
    "assets/ilan-fotograflari/216/8.png",
    "assets/ilan-fotograflari/216/9.png",
    "assets/ilan-fotograflari/216/10.png",
    "assets/ilan-fotograflari/216/11.png",
    "assets/ilan-fotograflari/216/12.png",
    "assets/ilan-fotograflari/216/13.png",
    "assets/ilan-fotograflari/216/14.png",
    "assets/ilan-fotograflari/216/15.png",
    "assets/ilan-fotograflari/216/16.png",
    "assets/ilan-fotograflari/216/17.png",



    ],
    mapsEmbedUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1505.7009228110846!2d29.056918190672775!3d40.994577004989985!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac7edf6181ec5%3A0xa301cfeacb8d4a91!2sBaysa%C5%9F%20%C4%B0stanbul%20216%20Deluxe%20Residence!5e0!3m2!1sen!2str!4v1778933986004!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Kadıköy Fikirtepe’de, Baysaş İstanbul 216 projesinde yer alan satılık 2+1 fırsat daire; Millet Bahçesi ve Adalar manzarasına sahip özel blokta bulunmaktadır. Toplu ulaşıma kolay erişim sağlayan projede yer alan full eşyalı dairemiz, kare ve kullanışlı oda planıyla konforlu bir yaşam sunmaktadır. Bölgede dönüşüm çalışmaları hızla tamamlanmakta olup Fikirtepe’nin yükselen değerlerinden biri olan İstanbul 216 projesinde bu fiyat seviyelerinde fırsat bulmak giderek zorlaşmaktadır. Projede 4.500 m² yeşil alan, sauna, buhar odası, hamam, açık ve kapalı yüzme havuzu, fitness salonu, çocuk oyun alanları, açık/kapalı otopark ve 7/24 güvenlik gibi sosyal olanaklar bulunmaktadır. Ayrıca Ünalan Metro, Uzunçayır Metrobüs ve İETT duraklarına yürüme mesafesinde merkezi bir konuma sahiptir. Detaylı bilgi ve randevu için: Tek Yetkili Turyap Ataşehir İmza – Erol Erdoğar.",
    specs: [
      { label: "İlan No", value: "1313961115" },
      { label: "İlan Tarihi", value: "14 Mayıs 2026" },
      { label: "Emlak tipi", value: "Satılık daire" },
      { label: "m² (Brüt / Net)", value: "90 / 70" },
      { label: "Oda sayısı", value: "2+1" },
      { label: "Bina yaşı", value: "6–10 arası" },
      { label: "Bulunduğu kat", value: "16" },
      { label: "Kat sayısı", value: "30 ve üzeri" },
      { label: "Isıtma", value: "Merkezi (Pay Ölçer)" },
      { label: "Banyo Sayısı", value: "1" },
      { label: "Mutfak", value: "Açık (Amerikan)" },
      { label: "Balkon", value: "Yok" },
      { label: "Asansör", value: "Var" },
      { label: "Otopark", value: "Açık & Kapalı Otopark" },
      { label: "Eşyalı", value: "Hayır" },
      { label: "Kullanım Durumu", value: "Boş" },
      { label: "Site İçerisinde", value: "Evet" },
      { label: "Site Adı", value: "İstanbul 216" },
      { label: "Aidat (TL)", value: "Belirtilmemiş" },
      { label: "Krediye Uygun", value: "Evet" },
      { label: "Enerji Kimlik Belgesi", value: "Belirtilmemiş" },
      { label: "Tapu Durumu", value: "Kat Mülkiyetli" },
      { label: "Kimden", value: "Emlak Ofisinden" },
      { label: "Takas", value: "Hayır" },
    ],
  },
  {
    id: "24",
    type: "satilik",
    title: "Kadıköy Pırlanta Rezidans Balkonlu Satılık 3+1 Fırsat Daire",
    price: "15.250.000 TL",
    location: "İstanbul / Kadıköy / Fikirtepe Mah.",
    listingDate: "15 Mayıs 2026",
    cardLocationShort: "İstanbul / Kadıköy",
    cardArea: "108 m²",
    cardRooms: "3+1",
    photos: [

       "assets/ilan-fotograflari/pirlanta/1.png",
       "assets/ilan-fotograflari/pirlanta/2.png",
       "assets/ilan-fotograflari/pirlanta/3.png",
       "assets/ilan-fotograflari/pirlanta/4.png",
       "assets/ilan-fotograflari/pirlanta/5.png",
       "assets/ilan-fotograflari/pirlanta/6.png",
       "assets/ilan-fotograflari/pirlanta/7.png",
       "assets/ilan-fotograflari/pirlanta/8.png",
       "assets/ilan-fotograflari/pirlanta/9.png",
       "assets/ilan-fotograflari/pirlanta/10.png",
       "assets/ilan-fotograflari/pirlanta/11.png",
       "assets/ilan-fotograflari/pirlanta/12.png",
       "assets/ilan-fotograflari/pirlanta/13.png",
       "assets/ilan-fotograflari/pirlanta/14.png",
       "assets/ilan-fotograflari/pirlanta/15.png",
       "assets/ilan-fotograflari/pirlanta/16.png",
       "assets/ilan-fotograflari/pirlanta/17.png",
       "assets/ilan-fotograflari/pirlanta/18.png",
       "assets/ilan-fotograflari/pirlanta/19.png",
       "assets/ilan-fotograflari/pirlanta/20.png",
       "assets/ilan-fotograflari/pirlanta/21.png",
       "assets/ilan-fotograflari/pirlanta/22.png",
       "assets/ilan-fotograflari/pirlanta/23.png",
       "assets/ilan-fotograflari/pirlanta/24.png",


    ],
    mapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1790.7065538302634!2d29.053549538472602!3d40.99029490003335!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cac78d03755191%3A0x1db49312c4e4e0ff!2sDiamond%20G%C3%B6ztepe!5e0!3m2!1sen!2str!4v1778934557954!5m2!1sen!2str",
    videoUrl: "",
    description:
      "Kadıköy Fikirtepe’de, Pırlanta Rezidans projesinde yer alan balkonlu satılık 3+1 fırsat daire; Marmara Üniversitesi ve Süleyman Yalçın Şehir Hastanesi girişine yakın, toplu ulaşıma kolay erişim sağlayan merkezi bir konumda bulunmaktadır. Kaliteyi arayanlara özel olarak tasarlanan dairemiz; balkon, ebeveyn banyosu ve çamaşır odası gibi ayrıcalıklı özelliklere sahiptir. Bankalar, marketler ve hastaneler yanı başında yer almaktadır. 3 bloktan oluşan projede toplam 446 konut ve 34 ticari ünite bulunmakta olup, açık ve kapalı yüzme havuzları, fitness salonu, sauna, hamam, sosyal tesisler, geniş peyzaj alanları, yürüyüş yolları, çocuk oyun alanları ve 750 araçlık kapalı otopark gibi sosyal donatılar sunulmaktadır. Kadıköy merkeze, sahile ve toplu taşımaya yakın konumuyla Pırlanta Göztepe; şehir yaşamında konfor, yatırım açısından değer ve aileler için güvenli bir yaşam sunmaktadır. Not: Dairemiz şu anda kiracılı olup tahliye süreci uzlaşma aşamasındadır. Sunumlar randevu ile yapılmaktadır. Tek Yetkili: Turyap Ataşehir İmza – Erol Erdoğar.",
    specs: [
      { label: "İlan No", value: "1317127111" },
      { label: "İlan Tarihi", value: "15 Mayıs 2026" },
      { label: "Emlak tipi", value: "Satılık daire" },
      { label: "m² (Brüt / Net)", value: "108 / 89" },
      { label: "Oda sayısı", value: "3+1" },
      { label: "Bina yaşı", value: "6–10 arası" },
      { label: "Bulunduğu kat", value: "7" },
      { label: "Kat sayısı", value: "23" },
      { label: "Isıtma", value: "Merkezi (Pay Ölçer)" },
      { label: "Banyo Sayısı", value: "2" },
      { label: "Mutfak", value: "Kapalı" },
      { label: "Balkon", value: "Var" },
      { label: "Asansör", value: "Var" },
      { label: "Otopark", value: "Yok" },
      { label: "Eşyalı", value: "Hayır" },
      { label: "Kullanım Durumu", value: "Kiracılı" },
      { label: "Site İçerisinde", value: "Evet" },
      { label: "Site Adı", value: "Pırlanta Göztepe" },
      { label: "Aidat (TL)", value: "Belirtilmemiş" },
      { label: "Krediye Uygun", value: "Evet" },
      { label: "Enerji Kimlik Belgesi", value: "Belirtilmemiş" },
      { label: "Tapu Durumu", value: "Kat Mülkiyetli" },
      { label: "Kimden", value: "Emlak Ofisinden" },
      { label: "Takas", value: "Hayır" },
    ],
  },
];
